name: dart_airtable
description: Dart library for working and interacting with the Airtable API 
version: 2.0.0
homepage: https://www.github.com/deriegle/dart-airtable

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  http: ^1.2.2
  meta: ^1.15.0

dev_dependencies:
  flutter_dotenv: ^5.1.0
  lints: ^4.0.0
  test: ^1.25.8
